/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { CargoRequirementsInput } from './cargoRequirementsInput';
import type { CargoType } from './cargoType';

/**
 * A single pallet unit assigned to a load plan.
 */
export interface CargoUnitResponse {
  /** Unique identifier of the pallet unit */
  id: string;
  /** Human-readable label of the pallet spec (e.g. "EPAL 1") */
  palletLabel: string;
  cargoType: CargoType;
  /**
   * Weight of the cargo on this pallet in kilograms
   * @exclusiveMinimum 0
   */
  weightKg: number;
  /**
   * Total height of pallet + cargo in millimetres
   * @exclusiveMinimum 0
   */
  totalHeightMm: number;
  requirements: CargoRequirementsInput;
}
