/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { CargoLoadPlanStatus } from './cargoLoadPlanStatus';
import type { CargoUnitResponse } from './cargoUnitResponse';
import type { TrailerReadModel } from './trailerReadModel';

/**
 * Full state of a cargo load plan.
 */
export interface LoadPlanResponse {
  /** Unique identifier of the load plan */
  id: string;
  status: CargoLoadPlanStatus;
  trailer: TrailerReadModel;
  /**
   * Currently used loading metres
   * @minimum 0
   */
  currentLdm: number;
  /**
   * Total weight of all assigned cargo units in kilograms
   * @minimum 0
   */
  plannedWeightKg: number;
  /** Cargo units assigned to this plan */
  units: CargoUnitResponse[];
}
