{
 "title": "Logs Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "level",
    "query": {}
   },
   {
    "name": "service",
    "query": {}
   },
   { "name": "phrase" }
  ]
 },
 "panels": [
  {
   "title": "Search by ...",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{ hostname=~\".+\", service=\"$service\" } |~ \"$phrase\""
    }
   ]
  },
  {
   "title": "Log Count Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=~\".+\"}[$__range])",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(status) (count_over_time({service=\"products-api\"} | json | status!=\"\" [5m]))\n# count_over_time({service=\"products-api\"} | json | status!=\"\" [5m])\n# {service=\"products-api\"} | json | status!=\"\"\n# {service=\"products-api\"} | json\n# {service=\"products-api\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Filter By Level",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{ hostname=~\".+\", service=\"$service\" } | json | level=\"$level\""
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{hostname=~\".+\", service=\"$service\" } | json | method=~\".+\" and url!=\"/favicon.ico\""
    }
   ]
  }
 ]
}