{
 "title": "PostgreSQL dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TOP Order Total Prices",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT customer_email, SUM(total_amount) AS total_spent FROM orders\nGROUP BY customer_email\nORDER BY total_spent DESC LIMIT 50;"
    }
   ]
  },
  {
   "title": "Products NEVER Ordered 😩",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT p.product_id, p.name, p.price, p.description, c.name AS category FROM products p\nLEFT JOIN order_items oi ON p.product_id = oi.product_id\nLEFT JOIN categories c ON p.category_id = c.category_id\nWHERE oi.item_id IS NULL;"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    -- Truncate the order_date to the start of the desired time interval.\n    -- Replace 'day' with 'hour', 'week', 'month', 'quarter', or 'year'\n    -- to change the aggregation level.\n    DATE_TRUNC('month', order_date) AS time_interval,\n    COUNT(order_id) AS orders_count\nFROM\n    orders\nGROUP BY\n    time_interval\nORDER BY\n    time_interval;"
    }
   ]
  },
  {
   "title": "Products",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * FROM products LIMIT 50 "
    }
   ]
  }
 ]
}