{
 "title": "(Prometheus) Products API Monitoring",
 "templating": {
  "list": [
   {
    "name": "route",
    "query": "label_values(http_request_duration_seconds_count, route)"
   },
   {
    "name": "method",
    "query": "label_values(http_request_duration_seconds_count, method)"
   }
  ]
 },
 "panels": [
  { "title": "Overview Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health (NO PARAMS HERE)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "health_status", "legendFormat": "HEALTHY" }
   ]
  },
  {
   "title": "Request Rate (STEP BY STEP TUTORIAL)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "# http_request_duration_seconds_count\n# http_request_duration_seconds_count{route=~\"$route\", method=~\"$method\"}\n# rate(http_request_duration_seconds_count{route=~\"$route\", method=~\"$method\"}[$__range])\n\nsum(rate(http_request_duration_seconds_count{route=~\"$route\", method=~\"$method\"}[$__range])) by (route, method)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Response Time Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{route=~\"$route\", method=~\"$method\"}[5m])) by (le, route))",
     "legendFormat": "p50 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{route=~\"$route\", method=~\"$method\"}[5m])) by (le, route))",
     "legendFormat": "p90 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{route=~\"$route\", method=~\"$method\"}[5m])) by (le, route))",
     "legendFormat": "p95 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{route=~\"$route\", method=~\"$method\"}[5m])) by (le, route))",
     "legendFormat": "p99 {{route}}"
    }
   ]
  },
  {
   "title": "Response Time Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{route=~\"$route\", method=~\"$method\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "(\n    # Satisfied requests: le <= 0.1\n    sum by (route) (rate(http_request_duration_seconds_bucket{le=\"0.1\", route=~\"$route\", method=~\"$method\"}[$__range]))\n    \n    # Tolerating requests: (le <= 0.3) - (le <= 0.1). This calculates the count between 0.1 and 0.3.\n    + \n    (\n        sum by (route) (rate(http_request_duration_seconds_bucket{le=\"0.3\", route=~\"$route\", method=~\"$method\"}[$__range]))\n        - \n        sum by (route) (rate(http_request_duration_seconds_bucket{le=\"0.1\", route=~\"$route\", method=~\"$method\"}[$__range]))\n    ) / 2\n)\n/\n#  Total requests: The overall count from the metric\nsum by (route) (rate(http_request_duration_seconds_count{route=~\"$route\", method=~\"$method\"}[$__range]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  { "title": "Error Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "# STEP BY STEP TUTORIAL\n# http_request_duration_seconds_count\n# http_request_duration_seconds_count{status_code=~'[45]..', route=~\"$route\", method=~\"$method\"}\n# sum(rate(http_request_duration_seconds_count{status_code=~'[45]..', route=~\"$route\", method=~\"$method\"}[$__range]))\n\nsum(rate(http_request_duration_seconds_count{status_code=~'[45]..', route=~\"$route\", method=~\"$method\"}[$__range]))\n/\nsum(rate(http_request_duration_seconds_count{route=~\"$route\", method=~\"$method\"}[$__range]))\n*\n100"
    }
   ]
  },
  {
   "title": "Error Count by Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status_code=~\"[45]..\", route=~\"$route\", method=~\"$method\"}[$__range])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Error Count by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status_code=~\"[45]..\", route=~\"$route\", method=~\"$method\"}[5m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Error Count by Route / Status Code (STEP BY STEP TUTORIAL)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "# http_request_duration_seconds_count\n# http_request_duration_seconds_count{status_code=~\"[45]..\"}\n# http_request_duration_seconds_count{status_code=~\"[45]..\", route=~\"$route\", method=~\"$method\"}\n# rate(http_request_duration_seconds_count{status_code=~\"[45]..\", route=~\"$route\", method=~\"$method\"}[$__range])\n\nsum(rate(http_request_duration_seconds_count{status_code=~\"[45]..\", route=~\"$route\", method=~\"$method\"}[$__range])) by (route, status_code)",
     "legendFormat": "{{route}} {{status_code}}"
    }
   ]
  },
  { "title": "Database Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Database Queries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname='products'}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Database Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{datname='products'}",
     "legendFormat": "Max Duration"
    }
   ]
  }
 ]
}