/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List customers
         * @description Returns a paginated list of customers. Supports optional full-text search by first or last name.
         */
        get: operations["getCustomers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get customer by ID
         * @description Returns a single customer with their full details and a summary of associated transportation orders.
         */
        get: operations["getCustomerById"];
        put?: never;
        post?: never;
        /**
         * Delete a customer
         * @description Permanently deletes a customer by their ID.
         */
        delete: operations["deleteCustomer"];
        options?: never;
        head?: never;
        /**
         * Update customer name
         * @description Partially updates a customer's first and/or last name. Uses optimistic locking – the request must include the current `version` value. If the resource was modified by another request since it was last read, a 409 conflict is returned.
         */
        patch: operations["patchCustomer"];
        trace?: never;
    };
    "/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List vehicles
         * @description Returns a paginated list of all vehicles.
         */
        get: operations["getVehicles"];
        put?: never;
        /**
         * Create a vehicle
         * @description Creates a new vehicle record.
         */
        post: operations["createVehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get vehicle by ID
         * @description Returns a single vehicle by its numeric ID.
         */
        get: operations["getVehicleById"];
        /**
         * Update a vehicle
         * @description Replaces vehicle data. All fields are optional – only provided fields are updated.
         */
        put: operations["updateVehicle"];
        post?: never;
        /**
         * Delete a vehicle
         * @description Permanently deletes a vehicle by its ID.
         */
        delete: operations["deleteVehicle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List drivers
         * @description Returns a list of all drivers (up to 100). No pagination.
         */
        get: operations["getDrivers"];
        put?: never;
        /**
         * Create a driver
         * @description Creates a new driver record. All fields are optional.
         */
        post: operations["createDriver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get driver by ID
         * @description Returns a single driver with their associated driver licenses.
         */
        get: operations["getDriverById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transportation-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List transportation orders
         * @description Returns a list of transportation orders, optionally filtered by customer ID. Results are ordered by order_date descending, limited to 100 items.
         */
        get: operations["getTransportationOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List notifications by user
         * @description Returns a paginated list of notifications for the given user. Results are ordered by created_at descending.
         */
        get: operations["getNotificationsByUserId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server status
         * @description Returns a plain-text message with server start time and uptime.
         */
        get: operations["getServerStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns a JSON object indicating the service is healthy. Used by load balancers and monitoring.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Pagination metadata attached to list responses. */
        Pagination: {
            /**
             * @description Current page number (1-based)
             * @example 1
             */
            page: number;
            /**
             * @description Number of items per page
             * @example 20
             */
            limit: number;
            /**
             * @description Total number of records across all pages
             * @example 50
             */
            total: number;
            /**
             * @description Total number of pages
             * @example 3
             */
            totalPages: number;
        };
        /** @description Standard error envelope returned on 4xx / 5xx responses. */
        ErrorResponse: {
            /**
             * @description Human-readable error message.
             * @example Vehicle not found
             */
            error: string;
        };
        /** @description A single customer record as returned in list responses. */
        CustomerListItem: {
            /**
             * @description Unique customer identifier
             * @example 1
             */
            id: number;
            /**
             * @description Customer first name
             * @example Maida
             */
            first_name?: string | null;
            /**
             * @description Customer last name
             * @example Dach
             */
            last_name?: string | null;
            /**
             * @description Customer email address
             * @example forestraynor@bauch.io
             */
            email?: string | null;
            /**
             * @description Customer phone number
             * @example 8082482608
             */
            phone?: string | null;
            /**
             * @description Customer classification (e.g. BUSINESS, INDIVIDUAL)
             * @example BUSINESS
             */
            customer_type?: string | null;
            /** @description Hypermedia links for related resources */
            _links?: {
                /**
                 * @description URL to fetch transportation orders for this customer
                 * @example http://localhost:3000/transportation-orders?customer_id=1
                 */
                orders?: string;
            };
        };
        /** @description Paginated list of customers. */
        CustomerListResponse: {
            data: components["schemas"]["CustomerListItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** @description Brief summary of a transportation order linked to a customer. */
        CustomerOrderSummary: {
            /**
             * @description Order identifier
             * @example 472
             */
            id: number;
            /**
             * @description Human-readable order number
             * @example #00472
             */
            order_number: string;
            /**
             * Format: float
             * @description Order total amount
             * @example 43.19
             */
            amount: number;
            /**
             * @description Current order status
             * @example DELIVERED
             */
            status: string;
        };
        /** @description Full customer record including all fields and associated orders summary. */
        CustomerDetail: {
            /**
             * @description Unique customer identifier
             * @example 1
             */
            id: number;
            /**
             * @description Customer first name
             * @example Maida
             */
            first_name?: string | null;
            /**
             * @description Customer last name
             * @example Dach
             */
            last_name?: string | null;
            /**
             * @description Customer email address
             * @example forestraynor@bauch.io
             */
            email?: string | null;
            /**
             * @description Customer phone number
             * @example 8082482608
             */
            phone?: string | null;
            /**
             * @description Customer classification (e.g. BUSINESS, INDIVIDUAL)
             * @example BUSINESS
             */
            customer_type?: string | null;
            /**
             * @description Customer address
             * @example 75968 Villageshire, St. Louis, New Hampshire 86673
             */
            address?: string | null;
            /**
             * @description Optimistic locking version counter – must be passed in PATCH requests
             * @example 1
             */
            version: number;
            /** @description Summary of transportation orders associated with this customer */
            orders: components["schemas"]["CustomerOrderSummary"][];
        };
        /** @description Payload for partially updating a customer's name. `version` (optimistic lock) is required. At least one of `first_name` or `last_name` must be provided. */
        CustomerPatchInput: {
            /**
             * @description Current version of the customer record (used for optimistic locking)
             * @example 1
             */
            version: number;
            /**
             * @description New first name (optional – provide to update)
             * @example Maida
             */
            first_name?: string;
            /**
             * @description New last name (optional – provide to update)
             * @example Dach
             */
            last_name?: string;
        };
        /** @description Updated customer data returned after a successful PATCH. */
        CustomerPatchResponse: {
            /**
             * @description Unique customer identifier
             * @example 1
             */
            id: number;
            /**
             * @description Updated first name
             * @example Maida Updated
             */
            first_name?: string | null;
            /**
             * @description Updated last name
             * @example Dach
             */
            last_name?: string | null;
            /**
             * @description Incremented version number after the update
             * @example 2
             */
            version: number;
        };
        /** @description A single vehicle record as returned by the API. */
        Vehicle: {
            /**
             * @description Unique vehicle identifier
             * @example 1
             */
            id: number;
            /**
             * @description Vehicle manufacturer / brand
             * @example Suzuki
             */
            make?: string | null;
            /**
             * @description Vehicle model name
             * @example S4
             */
            model: string;
            /**
             * @description Manufacturing year
             * @example 2021
             */
            year?: number | null;
            /**
             * @description Fuel tank capacity in litres. Returned as a decimal string (e.g. "51.1") because Postgres numeric/decimal is serialised as a string by the pg driver.
             * @example 51.1
             */
            fuel_tank_capacity?: string | null;
        };
        /** @description Paginated list of vehicles. */
        VehicleListResponse: {
            data: components["schemas"]["Vehicle"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** @description Payload for creating a new vehicle. Only `model` is required. */
        VehicleCreateInput: {
            /**
             * @description Vehicle manufacturer / brand
             * @example Toyota
             */
            make?: string | null;
            /**
             * @description Vehicle model name
             * @example Corolla
             */
            model: string;
            /**
             * @description Manufacturing year
             * @example 2024
             */
            year?: number | null;
            /**
             * Format: float
             * @description Fuel tank capacity in litres (positive number)
             * @example 55
             */
            fuel_tank_capacity?: number | null;
        };
        /** @description Payload for updating an existing vehicle. All fields are optional (partial update). Provide only the fields you want to change. */
        VehicleUpdateInput: {
            /**
             * @description Vehicle manufacturer / brand
             * @example Toyota
             */
            make?: string | null;
            /**
             * @description Vehicle model name
             * @example Camry
             */
            model?: string;
            /**
             * @description Manufacturing year
             * @example 2025
             */
            year?: number | null;
            /**
             * Format: float
             * @description Fuel tank capacity in litres (positive number)
             * @example 60
             */
            fuel_tank_capacity?: number | null;
        };
        /** @description A single driver record as returned in list and create responses. */
        DriverListItem: {
            /**
             * @description Unique driver identifier
             * @example 1
             */
            id: number;
            /**
             * @description Driver first name
             * @example Matt
             */
            first_name?: string | null;
            /**
             * @description Driver last name
             * @example Jerde
             */
            last_name?: string | null;
            /**
             * @description Driver email address
             * @example celiawalker@swift.net
             */
            email?: string | null;
            /**
             * @description Driver phone number
             * @example 4111234962
             */
            phone?: string | null;
            /**
             * @description Contract type (e.g. CONTRACTOR, FULL_TIME)
             * @example CONTRACTOR
             */
            contract_type?: string | null;
            /**
             * @description Driver status (e.g. ON_ROUTE, ACTIVE, RESTING)
             * @example ON_ROUTE
             */
            status?: string | null;
        };
        /** @description Payload for creating a new driver. All fields are optional. */
        DriverCreateInput: {
            /**
             * @description Driver first name
             * @example Jan
             */
            first_name?: string | null;
            /**
             * @description Driver last name
             * @example Kowalski
             */
            last_name?: string | null;
            /**
             * @description Driver email address
             * @example jan.kowalski@example.com
             */
            email?: string | null;
            /**
             * @description Driver phone number
             * @example 1234567890
             */
            phone?: string | null;
            /**
             * @description Contract type (e.g. FULL_TIME, CONTRACTOR)
             * @example FULL_TIME
             */
            contract_type?: string | null;
            /**
             * @description Driver status
             * @example ACTIVE
             */
            status?: string | null;
        };
        /** @description Driver license record with license type details (returned in driver detail). */
        DriverLicense: {
            /**
             * @description License record identifier
             * @example 1
             */
            id?: number;
            /**
             * @description License document number
             * @example CXX232105
             */
            document_number?: string | null;
            /**
             * Format: date
             * @description License issue date (YYYY-MM-DD)
             * @example 2020-08-30
             */
            issue_date?: string | null;
            /**
             * Format: date
             * @description License expiry date (YYYY-MM-DD)
             * @example 2027-09-21
             */
            expiry_date?: string | null;
            /**
             * @description License status (e.g. active)
             * @example active
             */
            status?: string | null;
            /**
             * @description License type code
             * @example C
             */
            code?: string | null;
            /**
             * @description License type name
             * @example Prawo jazdy kat. C
             */
            name?: string | null;
            /**
             * @description License type description
             * @example Pojazdy ciężarowe powyżej 3,5t
             */
            description?: string | null;
        };
        /** @description Full driver record including associated licenses (returned by GET /drivers/{id}). */
        DriverDetail: {
            /**
             * @description Unique driver identifier
             * @example 1
             */
            id: number;
            /**
             * @description Driver first name
             * @example Matt
             */
            first_name?: string | null;
            /**
             * @description Driver last name
             * @example Jerde
             */
            last_name?: string | null;
            /**
             * @description Driver email address
             * @example celiawalker@swift.net
             */
            email?: string | null;
            /**
             * @description Driver phone number
             * @example 4111234962
             */
            phone?: string | null;
            /**
             * @description Contract type (e.g. CONTRACTOR, FULL_TIME)
             * @example CONTRACTOR
             */
            contract_type?: string | null;
            /**
             * @description Driver status
             * @example ON_ROUTE
             */
            status?: string | null;
            /** @description Associated driver licenses with type details */
            licenses: components["schemas"]["DriverLicense"][];
        };
        /** @description A single transportation order as returned by the API. */
        TransportationOrder: {
            /**
             * @description Unique order identifier
             * @example 472
             */
            id: number;
            /**
             * @description Human-readable order number (e.g.
             * @example #00472
             */
            order_number: string;
            /**
             * @description ID of the customer who placed the order
             * @example 1
             */
            customer_id: number;
            /**
             * @description Order status (e.g. DELIVERED, PENDING)
             * @example DELIVERED
             */
            status: string;
            /**
             * @description Order total amount. Returned as a decimal string (e.g. "43.19") because Postgres numeric is serialised as a string by the pg driver.
             * @example 43.19
             */
            amount: string;
            /**
             * Format: date-time
             * @description When the order was placed (ISO 8601)
             * @example 2025-11-25T22:31:47.000Z
             */
            order_date: string;
            /**
             * Format: date-time
             * @description Expected delivery date (ISO 8601; Postgres date may be serialised with time component)
             * @example 2025-12-02T00:00:00.000Z
             */
            expected_delivery?: string | null;
            /**
             * @description Delivery street address
             * @example 6806 East Landchester, Plano, Utah 10652
             */
            shipping_address?: string | null;
            /**
             * @description Delivery city
             * @example Plano
             */
            shipping_city?: string | null;
            /**
             * @description Delivery state or region
             * @example Utah
             */
            shipping_state?: string | null;
            /**
             * @description Delivery postal code
             * @example 10652
             */
            shipping_zip_code?: string | null;
            /**
             * @description Shipping method name
             * @example Standard Delivery
             */
            shipping_method?: string | null;
            /**
             * @description Carrier tracking number
             * @example SR0472
             */
            tracking_number?: string | null;
        };
        /** @description A single notification as returned by the API. */
        Notification: {
            /**
             * @description Unique notification identifier
             * @example 115
             */
            id: number;
            /**
             * @description ID of the user who receives the notification
             * @example 1
             */
            user_id: number;
            /**
             * @description Notification type (e.g. warning, success)
             * @example warning
             */
            type: string;
            /**
             * @description Notification message content
             * @example Low fuel alert for assigned truck
             */
            message: string;
            /**
             * Format: date-time
             * @description When the notification was created (ISO 8601)
             * @example 2026-03-13T19:10:40.000Z
             */
            created_at: string;
            /**
             * @description Whether the notification has been read
             * @example false
             */
            is_read: boolean;
        };
        /** @description Paginated list of notifications. */
        NotificationListResponse: {
            data: components["schemas"]["Notification"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** @description Health check response body. */
        HealthResponse: {
            /**
             * @description Health status (always "ok" when the service is running)
             * @example ok
             */
            status: string;
            /**
             * @description Service name (from SERVICE_NAME env or default tms-api)
             * @example tms-api
             */
            service: string;
        };
    };
    responses: {
        /** @description An unexpected server-side error occurred. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /**
         * @description Page number (1-based)
         * @example 1
         */
        PageParam: number;
        /**
         * @description Number of items per page (max 100)
         * @example 20
         */
        LimitParam: number;
        /**
         * @description Numeric resource identifier
         * @example 1
         */
        PathIdParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCustomers: {
        parameters: {
            query?: {
                /**
                 * @description Page number (1-based)
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Number of items per page (max 100)
                 * @example 20
                 */
                limit?: components["parameters"]["LimitParam"];
                /**
                 * @description Filter customers by first or last name prefix (case-insensitive)
                 * @example an
                 */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of customers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": 1,
                     *           "first_name": "Maida",
                     *           "last_name": "Dach",
                     *           "email": "forestraynor@bauch.io",
                     *           "phone": "8082482608",
                     *           "customer_type": "BUSINESS",
                     *           "_links": {
                     *             "orders": "http://localhost:3000/transportation-orders?customer_id=1"
                     *           }
                     *         },
                     *         {
                     *           "id": 2,
                     *           "first_name": "Christelle",
                     *           "last_name": "Koepp",
                     *           "email": "jazminfadel@klein.io",
                     *           "phone": "5768528684",
                     *           "customer_type": "INDIVIDUAL",
                     *           "_links": {
                     *             "orders": "http://localhost:3000/transportation-orders?customer_id=2"
                     *           }
                     *         }
                     *       ],
                     *       "pagination": {
                     *         "page": 1,
                     *         "limit": 20,
                     *         "total": 500,
                     *         "totalPages": 25
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["CustomerListResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getCustomerById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Numeric resource identifier
                 * @example 1
                 */
                id: components["parameters"]["PathIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "first_name": "Maida",
                     *       "last_name": "Dach",
                     *       "email": "forestraynor@bauch.io",
                     *       "phone": "8082482608",
                     *       "customer_type": "BUSINESS",
                     *       "address": "75968 Villageshire, St. Louis, New Hampshire 86673",
                     *       "version": 1,
                     *       "orders": [
                     *         {
                     *           "id": 472,
                     *           "order_number": "#00472",
                     *           "amount": 43.19,
                     *           "status": "DELIVERED"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            /** @description No customer exists with the given ID. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Customer not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Numeric resource identifier
                 * @example 1
                 */
                id: components["parameters"]["PathIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer deleted successfully – no body returned. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No customer exists with the given ID. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Customer not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    patchCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Numeric resource identifier
                 * @example 1
                 */
                id: components["parameters"]["PathIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "version": 1,
                 *       "first_name": "Maida",
                 *       "last_name": "Dach"
                 *     }
                 */
                "application/json": components["schemas"]["CustomerPatchInput"];
            };
        };
        responses: {
            /** @description Customer updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "first_name": "Maida Updated",
                     *       "last_name": "Dach",
                     *       "version": 2
                     *     }
                     */
                    "application/json": components["schemas"]["CustomerPatchResponse"];
                };
            };
            /** @description Request payload is missing required fields or contains invalid values (e.g. missing version, no name field provided). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No customer exists with the given ID. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Customer not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Version conflict – the customer was modified by another request. Fetch the latest version and retry. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Version conflict – resource was modified by another request. Fetch the latest version and retry."
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getVehicles: {
        parameters: {
            query?: {
                /**
                 * @description Page number (1-based)
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Number of items per page (max 100)
                 * @example 20
                 */
                limit?: components["parameters"]["LimitParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of vehicles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": 1,
                     *           "make": "Suzuki",
                     *           "model": "S4",
                     *           "year": 2021,
                     *           "fuel_tank_capacity": "51.1"
                     *         },
                     *         {
                     *           "id": 2,
                     *           "make": "Volvo",
                     *           "model": "S80 Fwd",
                     *           "year": 2022,
                     *           "fuel_tank_capacity": "52.2"
                     *         }
                     *       ],
                     *       "pagination": {
                     *         "page": 1,
                     *         "limit": 20,
                     *         "total": 50,
                     *         "totalPages": 3
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["VehicleListResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    createVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "make": "Toyota",
                 *       "model": "Corolla",
                 *       "year": 2024,
                 *       "fuel_tank_capacity": 55
                 *     }
                 */
                "application/json": components["schemas"]["VehicleCreateInput"];
            };
        };
        responses: {
            /** @description Vehicle created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 51,
                     *       "make": "Toyota",
                     *       "model": "Corolla",
                     *       "year": 2024,
                     *       "fuel_tank_capacity": "55.0"
                     *     }
                     */
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            /** @description Request payload has an invalid structure or contains missing/invalid fields. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getVehicleById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Numeric resource identifier
                 * @example 1
                 */
                id: components["parameters"]["PathIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vehicle found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "make": "Suzuki",
                     *       "model": "S4",
                     *       "year": 2021,
                     *       "fuel_tank_capacity": "51.1"
                     *     }
                     */
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            /** @description The provided ID is missing or has an invalid format. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No vehicle exists with the given ID. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Vehicle not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    updateVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Numeric resource identifier
                 * @example 1
                 */
                id: components["parameters"]["PathIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "make": "Toyota",
                 *       "model": "Camry",
                 *       "year": 2025,
                 *       "fuel_tank_capacity": 60
                 *     }
                 */
                "application/json": components["schemas"]["VehicleUpdateInput"];
            };
        };
        responses: {
            /** @description Vehicle updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "make": "Toyota",
                     *       "model": "Camry",
                     *       "year": 2025,
                     *       "fuel_tank_capacity": "60.0"
                     *     }
                     */
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            /** @description Request payload has an invalid structure or contains missing/invalid fields. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No vehicle exists with the given ID, or the update produced no result. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Vehicle not found or invalid data"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Numeric resource identifier
                 * @example 1
                 */
                id: components["parameters"]["PathIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vehicle deleted successfully – no body returned. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No vehicle exists with the given ID. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Vehicle not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getDrivers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of drivers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": 1,
                     *         "first_name": "Matt",
                     *         "last_name": "Jerde",
                     *         "email": "celiawalker@swift.net",
                     *         "phone": "4111234962",
                     *         "contract_type": "CONTRACTOR",
                     *         "status": "ON_ROUTE"
                     *       },
                     *       {
                     *         "id": 2,
                     *         "first_name": "Mekhi",
                     *         "last_name": "Konopelski",
                     *         "email": "karsonschaefer@franecki.info",
                     *         "phone": "6392038976",
                     *         "contract_type": "CONTRACTOR",
                     *         "status": "RESTING"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["DriverListItem"][];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    createDriver: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "first_name": "Jan",
                 *       "last_name": "Kowalski",
                 *       "email": "jan.kowalski@example.com",
                 *       "phone": "1234567890",
                 *       "contract_type": "FULL_TIME",
                 *       "status": "ACTIVE"
                 *     }
                 */
                "application/json": components["schemas"]["DriverCreateInput"];
            };
        };
        responses: {
            /** @description Driver created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 21,
                     *       "first_name": "Jan",
                     *       "last_name": "Kowalski",
                     *       "email": "jan.kowalski@example.com",
                     *       "phone": "1234567890",
                     *       "contract_type": "FULL_TIME",
                     *       "status": "ACTIVE"
                     *     }
                     */
                    "application/json": components["schemas"]["DriverListItem"];
                };
            };
            /** @description Request payload has an invalid structure or contains missing/invalid fields. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getDriverById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Numeric resource identifier
                 * @example 1
                 */
                id: components["parameters"]["PathIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Driver found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "first_name": "Matt",
                     *       "last_name": "Jerde",
                     *       "email": "celiawalker@swift.net",
                     *       "phone": "4111234962",
                     *       "contract_type": "CONTRACTOR",
                     *       "status": "ON_ROUTE",
                     *       "licenses": [
                     *         {
                     *           "id": 1,
                     *           "document_number": "CXX232105",
                     *           "issue_date": "2020-08-30",
                     *           "expiry_date": "2027-09-21",
                     *           "status": "active",
                     *           "code": "C",
                     *           "name": "Prawo jazdy kat. C",
                     *           "description": "Pojazdy ciężarowe powyżej 3,5t"
                     *         },
                     *         {
                     *           "id": 2,
                     *           "document_number": "C+E728699",
                     *           "issue_date": "2023-01-07",
                     *           "expiry_date": "2028-01-07",
                     *           "status": "active",
                     *           "code": "C+E",
                     *           "name": "Prawo jazdy kat. C+E",
                     *           "description": "Ciągnik siodłowy z naczepą"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["DriverDetail"];
                };
            };
            /** @description No driver exists with the given ID. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Driver not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getTransportationOrders: {
        parameters: {
            query?: {
                /**
                 * @description Filter orders by customer ID. When omitted, returns all orders.
                 * @example 1
                 */
                customer_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of transportation orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": 472,
                     *         "order_number": "#00472",
                     *         "customer_id": 1,
                     *         "status": "DELIVERED",
                     *         "amount": "43.19",
                     *         "order_date": "2025-11-25T22:31:47.000Z",
                     *         "expected_delivery": "2025-12-02T00:00:00.000Z",
                     *         "shipping_address": "6806 East Landchester, Plano, Utah 10652",
                     *         "shipping_city": "Plano",
                     *         "shipping_state": "Utah",
                     *         "shipping_zip_code": "10652",
                     *         "shipping_method": "Standard Delivery",
                     *         "tracking_number": "SR0472"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["TransportationOrder"][];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getNotificationsByUserId: {
        parameters: {
            query: {
                /**
                 * @description User ID to fetch notifications for. Required.
                 * @example 1
                 */
                userId: number;
                /**
                 * @description Page number (1-based)
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Number of items per page (max 100)
                 * @example 20
                 */
                limit?: components["parameters"]["LimitParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": 115,
                     *           "user_id": 1,
                     *           "type": "warning",
                     *           "message": "Low fuel alert for assigned truck",
                     *           "created_at": "2026-03-13T19:10:40.000Z",
                     *           "is_read": false
                     *         },
                     *         {
                     *           "id": 14,
                     *           "user_id": 1,
                     *           "type": "warning",
                     *           "message": "Low fuel alert for assigned truck",
                     *           "created_at": "2026-03-12T22:49:04.000Z",
                     *           "is_read": false
                     *         },
                     *         {
                     *           "id": 77,
                     *           "user_id": 1,
                     *           "type": "success",
                     *           "message": "Payment received successfully",
                     *           "created_at": "2026-03-11T21:38:45.000Z",
                     *           "is_read": true
                     *         }
                     *       ],
                     *       "pagination": {
                     *         "page": 1,
                     *         "limit": 3,
                     *         "total": 4,
                     *         "totalPages": 2
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
            /** @description The userId query parameter is missing or invalid (must be a positive integer). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getServerStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server status (plain text) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "service": "tms-api"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
