config:
  target: "http://localhost:3000"
  phases:
    - name: "Ramp up to peak"
      duration: 15
      arrivalRate: 50
      rampTo: 10
      maxVusers: 5000

    - name: "Sustain peak load"
      duration: 30
      arrivalRate: 20
      maxVusers: 5000

    - name: "Ramp down"
      duration: 15
      arrivalRate: 10
      rampTo: 0
      maxVusers: 5000

scenarios:
  - name: "Product browsing + creation flow"
    flow:
      - get:
          url: "/products"
      - think: 3
      - get:
          url: "/products/1"
      - post:
          url: "/products"
          json:
            name: "Load Test Product"
            price: 49.99
      - think: 2
