/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetTransportationOrdersParams,
  TransportationOrder
} from '../model';




  export const getTransportationOrders = (axiosInstance: AxiosInstance = axios) => {
/**
 * Returns a list of transportation orders, optionally filtered by customer ID. Results are ordered by order_date descending, limited to 100 items.
 * @summary List transportation orders
 */
const getTransportationOrders = (
    params?: GetTransportationOrdersParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TransportationOrder[]>> => {
    return axiosInstance.get(
      `/transportation-orders`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {getTransportationOrders}};
export type GetTransportationOrdersResult = AxiosResponse<TransportationOrder[]>
