{
 "title": "Logs Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Log Count Over Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=~\".+\"}[15m])"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=~\".+\"} | json | method=~\".+\" and url!=\"/favicon.ico\""
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{host=~\".+\"}"
    }
   ]
  },
  {
   "title": "API Request Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{job=\"products-api\"} | json"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{host=~\".+\"} |~ \"(?i)ErRoR\""
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({job=\"products-api\"} | json | status!=\"\" [5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}